package config

import "os"

var (
	DDB_PAIRING_CONTEXT_TABLE    string
	DDB_CONNECTION_CONTEXT_TABLE string
	DDB_CONNECTION_SMS_TABLE     string
	IP_API_ENDPOINT              string
)

func LoadConfig() {
	DDB_PAIRING_CONTEXT_TABLE = os.Getenv("DDB_PAIRING_CONTEXT_TABLE")
	DDB_CONNECTION_CONTEXT_TABLE = os.Getenv("DDB_CONNECTION_CONTEXT_TABLE")
	DDB_CONNECTION_SMS_TABLE = os.Getenv("DDB_CONNECTION_SMS_TABLE")
	IP_API_ENDPOINT = os.Getenv("IP_API_ENDPOINT")
}
